import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { PageWrapper } from "@/components";

export const metadata: Metadata = {
  title: "Dung Vo Truong",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.className} scroll-smooth scroll-p-[72px]`}>
      <body>
        <PageWrapper>
          {children}
        </PageWrapper>
      </body>
    </html>
  );
}
